name: Release
# 触发方式
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: read  # 允许读取仓库内容，包括 Releases
      issues: write    # 如果需要操作 Issue
      pull-requests: write  # 如果需要操作 Pull Requests
    strategy:
      fail-fast: false
      matrix:
        # 我这里只需要两个平台，完整的可以参考官方的workflow
        platform: ['windows-latest']

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install frontend dependencies
        run: npm install
      # 修复环境变量传递并添加调试步骤
      - name: Debug environment
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        run: |
          if ($env:TAURI_PRIVATE_KEY) {
            Write-Host "Private key loaded: YES"
          } else {
            Write-Host "Private key loaded: NO"
          }
          if ($env:TAURI_PRIVATE_KEY_PASSWORD) {
            Write-Host "Private key password loaded: YES"
          } else {
            Write-Host "Private key password loaded: NO"
          }
      # 使用tauri actions
      - name: Build the app
        id: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用之前配置的私钥
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "app_v__VERSION__"
          releaseBody: ""
          releaseDraft: true
          prerelease: false
      - name: Install GitHub Actions dependencies
        run: npm install @actions/github @actions/core

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 运行自己的脚本
        run: node scripts/updater.mjs

