name: Release
# 触发方式
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    # 由于需要创建release所以需要设置写入权限
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # 我这里只需要两个平台，完整的可以参考官方的workflow
        platform: ['windows-latest']

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install frontend dependencies
        run: npm install
      - name: Debug environment
        run: |
          echo "Private key loaded: ${TAURI_SIGNING_PRIVATE_KEY:+YES}"
          echo "Private key password loaded: ${TAURI_SIGNING_PRIVATE_KEY_PASSWORD:+YES}"
      # 使用tauri actions
      - name: Build the app
        id: build
        uses: tauri-apps/tauri-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用之前配置的私钥
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # 使用之前配置的私钥密码
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "app_v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 运行自己的脚本
        run: node scripts/updater.mjs

