name: Release
# 触发方式
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    # 由于需要创建release所以需要设置写入权限
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        # 我这里只需要两个平台，完整的可以参考官方的workflow
        platform: ['windows-latest']

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install frontend dependencies
        run: npm install
      # 修复环境变量传递并添加调试步骤
      - name: Debug environment
        env:
          TAURI_SIGNING_PRIVATE_KEY: 'dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5TGtzVUttbG1QUGdXQXppOWhmeTRzbm9STENpOHlRckdsQXJXc20vZkoyMEFBQkFBQUFBQUFBQUFBQUlBQUFBQTN6bjhzK1Y5dnZBaDZ4ZElsVGx3UHVIdTc3RSt1MTF6L1hpVWs5YkNqTElNTG9jUEk4MjFOK1Z4TjI1WnJ1alcrbDg1dXBQK1VQMWQ5bEpPaGlTU2N5QzdwSEtUdlEzbHk3ZjZEZTRISElNYk13Q21RSjhHc0E3SmhmaVp6Y3ZubUdkU05JeEJBdDg9Cg=='
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: '13155488593'
        run: |
          if ($env:TAURI_SIGNING_PRIVATE_KEY) {
            Write-Host "Private key loaded: YES"
          } else {
            Write-Host "Private key loaded: NO"
          }
          if ($env:TAURI_SIGNING_PRIVATE_KEY_PASSWORD) {
            Write-Host "Private key password loaded: YES"
          } else {
            Write-Host "Private key password loaded: NO"
          }
      # 使用tauri actions
      - name: Build the app
        id: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 使用之前配置的私钥
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          # 使用之前配置的私钥密码
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "app_v__VERSION__"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false

      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 运行自己的脚本
        run: node scripts/updater.mjs

